#############################################################################
# Makefile for building: libqSAF.1.0.0.dylib
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  qSAF.pro
# Template: lib
# Command: /Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/qmake -o Makefile qSAF.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode-beta.app/Contents/Developer/usr/bin/gcc
CXX           = /Applications/Xcode-beta.app/Contents/Developer/usr/bin/g++
DEFINES       = -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../CC/include -I../../libs/qCC_db -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -F/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib
QMAKE         = /Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qSAF1.0.0
DISTDIR = /Users/xx/Studio/InnerEyes/CloudCompare/plugins/qSAF/.tmp/qSAF1.0.0
LINK          = /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/xx/Studio/InnerEyes/CloudCompare/plugins/qSAF/../../../Release/libs -Wl -Wl,-rpath,/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	libqSAF.1.dylib
LIBS          = $(SUBLIBS) -F/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib -L/Users/xx/Studio/InnerEyes/CloudCompare/plugins/qSAF/../../../Release/libs/ -lCC_CORE_LIB -lQCC_DB_LIB -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qSAF.cpp \
		../ccStdPluginInterface.cpp \
		ccSAFDlg.cpp qrc_qSAF.cpp \
		moc_qSAF.cpp \
		moc_ccSAFDlg.cpp
OBJECTS       = qSAF.o \
		ccStdPluginInterface.o \
		ccSAFDlg.o \
		qrc_qSAF.o \
		moc_qSAF.o \
		moc_ccSAFDlg.o
DIST          = /Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../../.qmake.stash \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf \
		qSAF.pro qSAF.h \
		../ccStdPluginInterface.h \
		../ccPluginInterface.h \
		../ccMainAppInterface.h \
		ccSAFDlg.h qSAF.cpp \
		../ccStdPluginInterface.cpp \
		ccSAFDlg.cpp
QMAKE_TARGET  = qSAF
DESTDIR       = ../../../Release/CloudCompare.app/Contents/plugins/
TARGET        = libqSAF.1.0.0.dylib
TARGETA       = ../../../Release/CloudCompare.app/Contents/plugins/libqSAF.a
TARGET0       = libqSAF.dylib
TARGETD       = libqSAF.1.0.0.dylib
TARGET1       = libqSAF.1.dylib
TARGET2       = libqSAF.1.0.dylib


first: all
####### Build rules

../../../Release/CloudCompare.app/Contents/plugins/$(TARGET): ui_SAFDlg.h $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../../../Release/CloudCompare.app/Contents/plugins/ || mkdir -p ../../../Release/CloudCompare.app/Contents/plugins/
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET)
	-$(MOVE) $(TARGET)  ../../../Release/CloudCompare.app/Contents/plugins/ 
	-$(DEL_FILE) ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET0)
	-$(DEL_FILE) ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET1)
	-$(DEL_FILE) ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET2)
	-$(MOVE) $(TARGET0) ../../../Release/CloudCompare.app/Contents/plugins/ 
	-$(MOVE) $(TARGET1) ../../../Release/CloudCompare.app/Contents/plugins/ 
	-$(MOVE) $(TARGET2) ../../../Release/CloudCompare.app/Contents/plugins/ 



staticlib: $(TARGETA)

$(TARGETA): ui_SAFDlg.h $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: qSAF.pro /Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf /Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf \
		../../../.qmake.stash \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf \
		qSAF.pro \
		qSAF.qrc \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile qSAF.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_pre.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qdevice.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/device_config.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/unix.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/mac.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/macx.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/sanitize.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/common/clang-mac.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/qconfig.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_functions.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt_config.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/spec_post.prf:
../../../.qmake.stash:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/sdk.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/toolchain.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_pre.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resolve_config.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/default_post.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/default_post.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qml_debug.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/warn_on.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qt.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/resources.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/moc.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/opengl.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/uic.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/unix/thread.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/qmake_use.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/file_copies.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/rez.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/testcase_targets.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/exceptions.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/yacc.prf:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/lex.prf:
qSAF.pro:
qSAF.qrc:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qSAF.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qSAF.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qSAF.h ../ccStdPluginInterface.h ../ccPluginInterface.h ../ccMainAppInterface.h ccSAFDlg.h $(DISTDIR)/
	$(COPY_FILE) --parents qSAF.cpp ../ccStdPluginInterface.cpp ccSAFDlg.cpp $(DISTDIR)/
	$(COPY_FILE) --parents SAFDlg.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET) 
	-$(DEL_FILE) ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET0) ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET1) ../../../Release/CloudCompare.app/Contents/plugins/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qSAF.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qSAF.cpp
qrc_qSAF.cpp: qSAF.qrc \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/rcc \
		icon.png
	/Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/rcc -name qSAF qSAF.qrc -o qrc_qSAF.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode-beta.app/Contents/Developer/usr/bin/g++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_qSAF.cpp moc_ccSAFDlg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qSAF.cpp moc_ccSAFDlg.cpp
moc_qSAF.cpp: ../ccStdPluginInterface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../libs/qCC_db/ccHObject.h \
		../../libs/qCC_db/ccObject.h \
		../../libs/qCC_db/ccSerializableObject.h \
		../../libs/qCC_db/ccLog.h \
		../../libs/qCC_db/qCC_db.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../CC/include/GenericChunkedArray.h \
		../../CC/include/CCPlatform.h \
		../../CC/include/CCShareable.h \
		../../CC/include/CCCoreLib.h \
		../../CC/include/CCTypes.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QFile \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDataStream \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdatastream.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVariant \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../libs/qCC_db/ccBBox.h \
		../../CC/include/SquareMatrix.h \
		../../CC/include/CCGeom.h \
		../../libs/qCC_db/ccDrawableObject.h \
		../../libs/qCC_db/ccGLDrawContext.h \
		../../libs/qCC_db/ccIncludeGL.h \
		../../libs/qCC_db/ccGLMatrix.h \
		../../libs/qCC_db/ccGLMatrixTpl.h \
		../../CC/include/CCConst.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QRegExp \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions_2_1 \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions_2_1.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../libs/qCC_db/ccMaterial.h \
		../../libs/qCC_db/ccColorTypes.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../ccPluginInterface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QIcon \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../ccMainAppInterface.h \
		qSAF.h \
		moc_predefs.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/moc
	/Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -I/Users/xx/Studio/InnerEyes/CloudCompare/plugins/qSAF -I/Users/xx/Studio/InnerEyes/CloudCompare/CC/include -I/Users/xx/Studio/InnerEyes/CloudCompare/libs/qCC_db -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib qSAF.h -o moc_qSAF.cpp

moc_ccSAFDlg.cpp: ui_SAFDlg.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ccSAFDlg.h \
		moc_predefs.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/moc
	/Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/mkspecs/macx-clang -I/Users/xx/Studio/InnerEyes/CloudCompare/plugins/qSAF -I/Users/xx/Studio/InnerEyes/CloudCompare/CC/include -I/Users/xx/Studio/InnerEyes/CloudCompare/libs/qCC_db -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.0/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib ccSAFDlg.h -o moc_ccSAFDlg.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_SAFDlg.h
compiler_uic_clean:
	-$(DEL_FILE) ui_SAFDlg.h
ui_SAFDlg.h: SAFDlg.ui \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/uic
	/Users/xx/Applications/Qt5.8.0/5.8/clang_64/bin/uic SAFDlg.ui -o ui_SAFDlg.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

qSAF.o: qSAF.cpp qSAF.h \
		../ccStdPluginInterface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../libs/qCC_db/ccHObject.h \
		../../libs/qCC_db/ccObject.h \
		../../libs/qCC_db/ccSerializableObject.h \
		../../libs/qCC_db/ccLog.h \
		../../libs/qCC_db/qCC_db.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../CC/include/GenericChunkedArray.h \
		../../CC/include/CCPlatform.h \
		../../CC/include/CCShareable.h \
		../../CC/include/CCCoreLib.h \
		../../CC/include/CCTypes.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QFile \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDataStream \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdatastream.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVariant \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../libs/qCC_db/ccBBox.h \
		../../CC/include/SquareMatrix.h \
		../../CC/include/CCGeom.h \
		../../libs/qCC_db/ccDrawableObject.h \
		../../libs/qCC_db/ccGLDrawContext.h \
		../../libs/qCC_db/ccIncludeGL.h \
		../../libs/qCC_db/ccGLMatrix.h \
		../../libs/qCC_db/ccGLMatrixTpl.h \
		../../CC/include/CCConst.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QRegExp \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions_2_1 \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions_2_1.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../libs/qCC_db/ccMaterial.h \
		../../libs/qCC_db/ccColorTypes.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../ccPluginInterface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QIcon \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../ccMainAppInterface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QtGui \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtguiglobal.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpen.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qregion.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QProgressDialog \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QElapsedTimer \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		ccSAFDlg.h \
		ui_SAFDlg.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../libs/qCC_db/ccGenericPointCloud.h \
		../../CC/include/GenericProgressCallback.h \
		../../CC/include/ReferenceCloud.h \
		../../CC/include/GenericIndexedCloudPersist.h \
		../../CC/include/GenericIndexedCloud.h \
		../../CC/include/GenericCloud.h \
		../../libs/qCC_db/ccGenericGLDisplay.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../libs/qCC_db/ccShiftedObject.h \
		../../libs/qCC_db/ccAdvancedTypes.h \
		../../libs/qCC_db/ccChunkedArray.h \
		../../libs/qCC_db/ccNormalCompressor.h \
		../../libs/qCC_db/ccBasicTypes.h \
		../../libs/qCC_db/ccOctree.h \
		../../CC/include/DgmOctree.h \
		../../CC/include/GenericOctree.h \
		../../libs/qCC_db/ccPointCloud.h \
		../../CC/include/ChunkedPointCloud.h \
		../../CC/include/PointProjectionTools.h \
		../../CC/include/CCToolbox.h \
		../../libs/qCC_db/ccNormalVectors.h \
		../../CC/include/GenericIndexedMesh.h \
		../../CC/include/GenericMesh.h \
		../../CC/include/GeometricalAnalysisTools.h \
		../../CC/include/Neighbourhood.h \
		../../CC/include/CCMiscTools.h \
		../../libs/qCC_db/ccColorScale.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QColor \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QList \
		../../libs/qCC_db/ccWaveform.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/Headers/QGLBuffer \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtOpenGL.framework/Headers/qglbuffer.h \
		../../libs/qCC_db/ccProgressDialog.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QAtomicInt \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qatomic.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../CC/include/ScalarField.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qSAF.o qSAF.cpp

ccStdPluginInterface.o: ../ccStdPluginInterface.cpp ../ccStdPluginInterface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		../../libs/qCC_db/ccHObject.h \
		../../libs/qCC_db/ccObject.h \
		../../libs/qCC_db/ccSerializableObject.h \
		../../libs/qCC_db/ccLog.h \
		../../libs/qCC_db/qCC_db.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../CC/include/GenericChunkedArray.h \
		../../CC/include/CCPlatform.h \
		../../CC/include/CCShareable.h \
		../../CC/include/CCCoreLib.h \
		../../CC/include/CCTypes.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QFile \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QDataStream \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qdatastream.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QVariant \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QSharedPointer \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../libs/qCC_db/ccBBox.h \
		../../CC/include/SquareMatrix.h \
		../../CC/include/CCGeom.h \
		../../libs/qCC_db/ccDrawableObject.h \
		../../libs/qCC_db/ccGLDrawContext.h \
		../../libs/qCC_db/ccIncludeGL.h \
		../../libs/qCC_db/ccGLMatrix.h \
		../../libs/qCC_db/ccGLMatrixTpl.h \
		../../CC/include/CCConst.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QRegExp \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLFunctions_2_1 \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglfunctions_2_1.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLContext \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QOpenGLWidget \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QSurfaceFormat \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QOpenGLTexture \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../libs/qCC_db/ccMaterial.h \
		../../libs/qCC_db/ccColorTypes.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../ccPluginInterface.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/QIcon \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../ccMainAppInterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ccStdPluginInterface.o ../ccStdPluginInterface.cpp

ccSAFDlg.o: ccSAFDlg.cpp ccSAFDlg.h \
		ui_SAFDlg.h \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Users/xx/Applications/Qt5.8.0/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ccSAFDlg.o ccSAFDlg.cpp

qrc_qSAF.o: qrc_qSAF.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qSAF.o qrc_qSAF.cpp

moc_qSAF.o: moc_qSAF.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qSAF.o moc_qSAF.cpp

moc_ccSAFDlg.o: moc_ccSAFDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ccSAFDlg.o moc_ccSAFDlg.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

